package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Achat generated by hbm2java
 */
@SuppressWarnings("serial")
public class Achat implements java.io.Serializable {

	private int numeroachat;
	private Fournisseur fournisseur;
	private Session session;
	private Etat etat;
	private BigDecimal montanttotalachatht;
	private BigDecimal montanttotalachatttc;
	private Date dateachat;
	private Set<Lignedachat> lignedachats = new HashSet<Lignedachat>(0);

	public Achat() {
	}

	public Achat(int numeroachat, Fournisseur fournisseur, Session session,
			Etat etat) {
		this.numeroachat = numeroachat;
		this.fournisseur = fournisseur;
		this.session = session;
		this.etat = etat;
	}

	public Achat(int numeroachat, Fournisseur fournisseur, Session session,
			Etat etat, BigDecimal montanttotalachatht,
			BigDecimal montanttotalachatttc, Date dateachat,
			Set<Lignedachat> lignedachats) {
		this.numeroachat = numeroachat;
		this.fournisseur = fournisseur;
		this.session = session;
		this.etat = etat;
		this.montanttotalachatht = montanttotalachatht;
		this.montanttotalachatttc = montanttotalachatttc;
		this.dateachat = dateachat;
		this.lignedachats = lignedachats;
	}

	public int getNumeroachat() {
		return this.numeroachat;
	}

	public void setNumeroachat(int numeroachat) {
		this.numeroachat = numeroachat;
	}

	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public BigDecimal getMontanttotalachatht() {
		return this.montanttotalachatht;
	}

	public void setMontanttotalachatht(BigDecimal montanttotalachatht) {
		this.montanttotalachatht = montanttotalachatht;
	}

	public BigDecimal getMontanttotalachatttc() {
		return this.montanttotalachatttc;
	}

	public void setMontanttotalachatttc(BigDecimal montanttotalachatttc) {
		this.montanttotalachatttc = montanttotalachatttc;
	}

	public Date getDateachat() {
		return this.dateachat;
	}

	public void setDateachat(Date dateachat) {
		this.dateachat = dateachat;
	}

	public Set<Lignedachat> getLignedachats() {
		return this.lignedachats;
	}

	public void setLignedachats(Set<Lignedachat> lignedachats) {
		this.lignedachats = lignedachats;
	}

}
