package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

/**
 * Categorie generated by hbm2java
 */
@SuppressWarnings("serial")
public class Categorie implements java.io.Serializable {

	private int idcategorie;
	private String designation;
	private Integer quantitestock;
	private Integer prixunitairevente;
	private Integer prixunitaireachat;
	private Integer quantiteIdeale;
	private Integer quantiteSecurite;

	public Categorie() {
	}

	public int getIdcategorie() {
		return this.idcategorie;
	}

	public void setIdcategorie(int idcategorie) {
		this.idcategorie = idcategorie;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public Integer getQuantitestock() {
		return this.quantitestock;
	}

	public void setQuantitestock(Integer quantitestock) {
		this.quantitestock = quantitestock;
	}

	public Integer getPrixunitairevente() {
		return this.prixunitairevente;
	}

	public void setPrixunitairevente(Integer prixunitairevente) {
		this.prixunitairevente = prixunitairevente;
	}

	public Integer getPrixunitaireachat() {
		return this.prixunitaireachat;
	}

	public void setPrixunitaireachat(Integer prixunitaireachat) {
		this.prixunitaireachat = prixunitaireachat;
	}

	/**
	 * @return the quantiteIdeale
	 */
	public Integer getQuantiteIdeale() {
		return quantiteIdeale;
	}

	/**
	 * @param quantiteIdeale
	 *            the quantiteIdeale to set
	 */
	public void setQuantiteIdeale(Integer quantiteIdeale) {
		this.quantiteIdeale = quantiteIdeale;
	}

	/**
	 * @return the quantiteSecurite
	 */
	public Integer getQuantiteSecurite() {
		return quantiteSecurite;
	}

	/**
	 * @param quantiteSecurite
	 *            the quantiteSecurite to set
	 */
	public void setQuantiteSecurite(Integer quantiteSecurite) {
		this.quantiteSecurite = quantiteSecurite;
	}

}
