package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Creditclient generated by hbm2java
 */
@SuppressWarnings("serial")
public class Creditclient implements java.io.Serializable {

	private int idcreditclient;
	private Client client;
	private Session session;
	private Etat etat;
	private BigDecimal montanttotalht;
	private BigDecimal montanttotalttc;
	private Date datecredit;
	private BigDecimal montantpaye;
	private Set<Lignedevente> lignedeventes = new HashSet<Lignedevente>(0);
	private Set<Payementcreditclient> payementcreditclients = new HashSet<Payementcreditclient>(
			0);
	private Set<Lignecreditvente> lignecreditventes = new HashSet<Lignecreditvente>(
			0);

	public Creditclient() {
	}

	public Creditclient(int idcreditclient, Client client, Session session,
			Etat etat) {
		this.idcreditclient = idcreditclient;
		this.client = client;
		this.session = session;
		this.etat = etat;
	}

	public Creditclient(int idcreditclient, Client client, Session session,
			Etat etat, BigDecimal montanttotalht, BigDecimal montanttotalttc,
			Date datecredit, BigDecimal montantpaye,
			Set<Lignedevente> lignedeventes,
			Set<Payementcreditclient> payementcreditclients,
			Set<Lignecreditvente> lignecreditventes) {
		this.idcreditclient = idcreditclient;
		this.client = client;
		this.session = session;
		this.etat = etat;
		this.montanttotalht = montanttotalht;
		this.montanttotalttc = montanttotalttc;
		this.datecredit = datecredit;
		this.montantpaye = montantpaye;
		this.lignedeventes = lignedeventes;
		this.payementcreditclients = payementcreditclients;
		this.lignecreditventes = lignecreditventes;
	}

	public int getIdcreditclient() {
		return this.idcreditclient;
	}

	public void setIdcreditclient(int idcreditclient) {
		this.idcreditclient = idcreditclient;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public BigDecimal getMontanttotalht() {
		return this.montanttotalht;
	}

	public void setMontanttotalht(BigDecimal montanttotalht) {
		this.montanttotalht = montanttotalht;
	}

	public BigDecimal getMontanttotalttc() {
		return this.montanttotalttc;
	}

	public void setMontanttotalttc(BigDecimal montanttotalttc) {
		this.montanttotalttc = montanttotalttc;
	}

	public Date getDatecredit() {
		return this.datecredit;
	}

	public void setDatecredit(Date datecredit) {
		this.datecredit = datecredit;
	}

	public BigDecimal getMontantpaye() {
		return this.montantpaye;
	}

	public void setMontantpaye(BigDecimal montantpaye) {
		this.montantpaye = montantpaye;
	}

	public Set<Lignedevente> getLignedeventes() {
		return this.lignedeventes;
	}

	public void setLignedeventes(Set<Lignedevente> lignedeventes) {
		this.lignedeventes = lignedeventes;
	}

	public Set<Payementcreditclient> getPayementcreditclients() {
		return this.payementcreditclients;
	}

	public void setPayementcreditclients(
			Set<Payementcreditclient> payementcreditclients) {
		this.payementcreditclients = payementcreditclients;
	}

	public Set<Lignecreditvente> getLignecreditventes() {
		return this.lignecreditventes;
	}

	public void setLignecreditventes(Set<Lignecreditvente> lignecreditventes) {
		this.lignecreditventes = lignecreditventes;
	}

}
