package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Creditfournisseur generated by hbm2java
 */
@SuppressWarnings("serial")
public class Creditfournisseur implements java.io.Serializable {

	private int idcreditfournisseur;
	private Fournisseur fournisseur;
	private Session session;
	private Etat etat;
	private BigDecimal montanttotalht;
	private BigDecimal montanttotalttc;
	private Date datecredit;
	private BigDecimal montantpaye;
	private Set<Payementcreditfournisseur> payementcreditfournisseurs = new HashSet<Payementcreditfournisseur>(
			0);
	private Set<Lignecreditachat> lignecreditachats = new HashSet<Lignecreditachat>(
			0);

	public Creditfournisseur() {
	}

	public Creditfournisseur(int idcreditfournisseur, Fournisseur fournisseur,
			Session session, Etat etat) {
		this.idcreditfournisseur = idcreditfournisseur;
		this.fournisseur = fournisseur;
		this.session = session;
		this.etat = etat;
	}

	public Creditfournisseur(int idcreditfournisseur, Fournisseur fournisseur,
			Session session, Etat etat, BigDecimal montanttotalht,
			BigDecimal montanttotalttc, Date datecredit,
			BigDecimal montantpaye,
			Set<Payementcreditfournisseur> payementcreditfournisseurs,
			Set<Lignecreditachat> lignecreditachats) {
		this.idcreditfournisseur = idcreditfournisseur;
		this.fournisseur = fournisseur;
		this.session = session;
		this.etat = etat;
		this.montanttotalht = montanttotalht;
		this.montanttotalttc = montanttotalttc;
		this.datecredit = datecredit;
		this.montantpaye = montantpaye;
		this.payementcreditfournisseurs = payementcreditfournisseurs;
		this.lignecreditachats = lignecreditachats;
	}

	public int getIdcreditfournisseur() {
		return this.idcreditfournisseur;
	}

	public void setIdcreditfournisseur(int idcreditfournisseur) {
		this.idcreditfournisseur = idcreditfournisseur;
	}

	public Fournisseur getFournisseur() {
		return this.fournisseur;
	}

	public void setFournisseur(Fournisseur fournisseur) {
		this.fournisseur = fournisseur;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public BigDecimal getMontanttotalht() {
		return this.montanttotalht;
	}

	public void setMontanttotalht(BigDecimal montanttotalht) {
		this.montanttotalht = montanttotalht;
	}

	public BigDecimal getMontanttotalttc() {
		return this.montanttotalttc;
	}

	public void setMontanttotalttc(BigDecimal montanttotalttc) {
		this.montanttotalttc = montanttotalttc;
	}

	public Date getDatecredit() {
		return this.datecredit;
	}

	public void setDatecredit(Date datecredit) {
		this.datecredit = datecredit;
	}

	public BigDecimal getMontantpaye() {
		return this.montantpaye;
	}

	public void setMontantpaye(BigDecimal montantpaye) {
		this.montantpaye = montantpaye;
	}

	public Set<Payementcreditfournisseur> getPayementcreditfournisseurs() {
		return this.payementcreditfournisseurs;
	}
 
	public void setPayementcreditfournisseurs(
			Set<Payementcreditfournisseur> payementcreditfournisseurs) {
		this.payementcreditfournisseurs = payementcreditfournisseurs;
	}

	public Set<Lignecreditachat> getLignecreditachats() {
		return this.lignecreditachats;
	}

	public void setLignecreditachats(Set<Lignecreditachat> lignecreditachats) {
		this.lignecreditachats = lignecreditachats;
	}

}
