package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Depense generated by hbm2java
 */
@SuppressWarnings("serial")
public class Depense  implements java.io.Serializable {


     private int iddepense;
     private Session session;
     private String libelledepense;
     private BigDecimal montantdepense;

    public Depense() {
    }

	
    public Depense(int iddepense, Session session) {
        this.iddepense = iddepense;
        this.session = session;
    }
    public Depense(int iddepense, Session session, String libelledepense, BigDecimal montantdepense) {
       this.iddepense = iddepense;
       this.session = session;
       this.libelledepense = libelledepense;
       this.montantdepense = montantdepense;
    }
   
    public int getIddepense() {
        return this.iddepense;
    }
    
    public void setIddepense(int iddepense) {
        this.iddepense = iddepense;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public String getLibelledepense() {
        return this.libelledepense;
    }
    
    public void setLibelledepense(String libelledepense) {
        this.libelledepense = libelledepense;
    }
    public BigDecimal getMontantdepense() {
        return this.montantdepense;
    }
    
    public void setMontantdepense(BigDecimal montantdepense) {
        this.montantdepense = montantdepense;
    }




}


