package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur {

	private int idfournisseur;
	private String nomFournisseur;
	private String prenomFournisseur;
	private String telephonefournisseur;

	public Fournisseur() {
	}

	public Fournisseur(int idfournisseur) {
		this.idfournisseur = idfournisseur;
	}

	public int getIdfournisseur() {
		return this.idfournisseur;
	}

	public void setIdfournisseur(int idfournisseur) {
		this.idfournisseur = idfournisseur;
	}

	/**
	 * @return the nomFournisseur
	 */
	public String getNomFournisseur() {
		return nomFournisseur;
	}

	/**
	 * @param nomFournisseur
	 *            the nomFournisseur to set
	 */
	public void setNomFournisseur(String nomFournisseur) {
		this.nomFournisseur = nomFournisseur;
	}

	/**
	 * @return the prenomFournisseur
	 */
	public String getPrenomFournisseur() {
		return prenomFournisseur;
	}

	/**
	 * @param prenomFournisseur
	 *            the prenomFournisseur to set
	 */
	public void setPrenomFournisseur(String prenomFournisseur) {
		this.prenomFournisseur = prenomFournisseur;
	}

	public String getTelephonefournisseur() {
		return this.telephonefournisseur;
	}

	public void setTelephonefournisseur(String telephonefournisseur) {
		this.telephonefournisseur = telephonefournisseur;
	}

}
