package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Lignedachat generated by hbm2java
 */
@SuppressWarnings("serial")
public class Lignedachat  implements java.io.Serializable {


     private Produit produit;
     private Achat achat;
     private Integer quantiteligneachat;
     private BigDecimal montantligneachatht;
     private BigDecimal montantligneventettc;

    public Lignedachat() {
    }

	
  
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Achat getAchat() {
        return this.achat;
    }
    
    public void setAchat(Achat achat) {
        this.achat = achat;
    }
    public Integer getQuantiteligneachat() {
        return this.quantiteligneachat;
    }
    
    public void setQuantiteligneachat(Integer quantiteligneachat) {
        this.quantiteligneachat = quantiteligneachat;
    }
    public BigDecimal getMontantligneachatht() {
        return this.montantligneachatht;
    }
    
    public void setMontantligneachatht(BigDecimal montantligneachatht) {
        this.montantligneachatht = montantligneachatht;
    }
    public BigDecimal getMontantligneventettc() {
        return this.montantligneventettc;
    }
    
    public void setMontantligneventettc(BigDecimal montantligneventettc) {
        this.montantligneventettc = montantligneventettc;
    }




}


