package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

/**
 * Lignedevente generated by hbm2java
 */
public class Lignedevente {
	private int idLigneDeVente;
	private Vente vente;
	private Categorie categorie;
	private Integer quantitelignevente;
	private Double montantligneventeht;
	private Double montantLigneVenteTva;
	private Double montantligneventettc;

	/**
	 * @return the montantLigneVenteTva
	 */
	public Double getMontantLigneVenteTva() {
		return montantLigneVenteTva;
	}

	/**
	 * @param montantLigneVenteTva
	 *            the montantLigneVenteTva to set
	 */
	public void setMontantLigneVenteTva(Double montantLigneVenteTva) {
		this.montantLigneVenteTva = montantLigneVenteTva;
	}

	public Lignedevente() {
	}

	/**
	 * @return the idLigneDeVente
	 */
	public int getIdLigneDeVente() {
		return idLigneDeVente;
	}

	/**
	 * @param idLigneDeVente
	 *            the idLigneDeVente to set
	 */
	public void setIdLigneDeVente(int idLigneDeVente) {
		this.idLigneDeVente = idLigneDeVente;
	}

	/**
	 * @return the categorie
	 */
	public Categorie getCategorie() {
		return categorie;
	}

	/**
	 * @param categorie
	 *            the categorie to set
	 */
	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	public Vente getVente() {
		return this.vente;
	}

	public void setVente(Vente vente) {
		this.vente = vente;
	}

	public Integer getQuantitelignevente() {
		return this.quantitelignevente;
	}

	public void setQuantitelignevente(Integer quantitelignevente) {
		this.quantitelignevente = quantitelignevente;
	}
	public Double getMontantligneventeht() {
		return this.montantligneventeht;
	}

	public void setMontantligneventeht(Double montantligneventeht) {
		this.montantligneventeht = montantligneventeht;
	}
	public Double getMontantligneventettc() {
		return this.montantligneventettc;
	}

	public void setMontantligneventettc(Double montantligneventettc) {
		this.montantligneventettc = montantligneventettc;
	}

}
