package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * Lignecreditachat generated by hbm2java
 */
@SuppressWarnings("serial")
public class Lignecreditachat implements java.io.Serializable {

	private Produit produit;
	private Creditfournisseur creditfournisseur;
	private Integer quantiteligneachat;
	private BigDecimal montantligneachatht;
	private BigDecimal montantligneachatttc;

	public Lignecreditachat() {
	}

	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}
	public Creditfournisseur getCreditfournisseur() {
		return this.creditfournisseur;
	}

	public void setCreditfournisseur(Creditfournisseur creditfournisseur) {
		this.creditfournisseur = creditfournisseur;
	}
	public Integer getQuantiteligneachat() {
		return this.quantiteligneachat;
	}

	public void setQuantiteligneachat(Integer quantiteligneachat) {
		this.quantiteligneachat = quantiteligneachat;
	}
	public BigDecimal getMontantligneachatht() {
		return this.montantligneachatht;
	}

	public void setMontantligneachatht(BigDecimal montantligneachatht) {
		this.montantligneachatht = montantligneachatht;
	}
	public BigDecimal getMontantligneachatttc() {
		return this.montantligneachatttc;
	}

	public void setMontantligneachatttc(BigDecimal montantligneachatttc) {
		this.montantligneachatttc = montantligneachatttc;
	}

}
