package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA



/**
 * Parametres generated by hbm2java
 */
@SuppressWarnings("serial")
public class Parametres  implements java.io.Serializable {


     private int dureeviemdp;
     private Integer longueurmdp;
     private Integer tentativemdp;
     private Integer tempsinactivitesmdp;
     private Double tauxtva;

    public Parametres() {
    }

    public Parametres(int dureeviemdp, Integer longueurmdp, Integer tentativemdp, Integer tempsinactivitesmdp, Double tauxtva) {
       this.dureeviemdp = dureeviemdp;
       this.longueurmdp = longueurmdp;
       this.tentativemdp = tentativemdp;
       this.tempsinactivitesmdp = tempsinactivitesmdp;
       this.tauxtva = tauxtva;
    }
   
    public int getDureeviemdp() {
        return this.dureeviemdp;
    }
    
    public void setDureeviemdp(int dureeviemdp) {
        this.dureeviemdp = dureeviemdp;
    }
    public Integer getLongueurmdp() {
        return this.longueurmdp;
    }
    
    public void setLongueurmdp(Integer longueurmdp) {
        this.longueurmdp = longueurmdp;
    }
    public Integer getTentativemdp() {
        return this.tentativemdp;
    }
    
    public void setTentativemdp(Integer tentativemdp) {
        this.tentativemdp = tentativemdp;
    }
    public Integer getTempsinactivitesmdp() {
        return this.tempsinactivitesmdp;
    }
    
    public void setTempsinactivitesmdp(Integer tempsinactivitesmdp) {
        this.tempsinactivitesmdp = tempsinactivitesmdp;
    }
    public Double getTauxtva() {
        return this.tauxtva;
    }
    
    public void setTauxtva(Double tauxtva) {
        this.tauxtva = tauxtva;
    }




}


