package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA



/**
 * PayementcreditfournisseurId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PayementcreditfournisseurId  implements java.io.Serializable {


     private int idcreditfournisseur;
     private int idsession;

    public PayementcreditfournisseurId() {
    }

    public PayementcreditfournisseurId(int idcreditfournisseur, int idsession) {
       this.idcreditfournisseur = idcreditfournisseur;
       this.idsession = idsession;
    }
   
    public int getIdcreditfournisseur() {
        return this.idcreditfournisseur;
    }
    
    public void setIdcreditfournisseur(int idcreditfournisseur) {
        this.idcreditfournisseur = idcreditfournisseur;
    }
    public int getIdsession() {
        return this.idsession;
    }
    
    public void setIdsession(int idsession) {
        this.idsession = idsession;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PayementcreditfournisseurId) ) return false;
		 PayementcreditfournisseurId castOther = ( PayementcreditfournisseurId ) other; 
         
		 return (this.getIdcreditfournisseur()==castOther.getIdcreditfournisseur())
 && (this.getIdsession()==castOther.getIdsession());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcreditfournisseur();
         result = 37 * result + this.getIdsession();
         return result;
   }   


}


