package com.mms.pojos;
// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA



/**
 * PayementcreditclientId generated by hbm2java
 */
@SuppressWarnings("serial")
public class PayementcreditclientId  implements java.io.Serializable {


     private int idcreditclient;
     private int idsession;

    public PayementcreditclientId() {
    }

    public PayementcreditclientId(int idcreditclient, int idsession) {
       this.idcreditclient = idcreditclient;
       this.idsession = idsession;
    }
   
    public int getIdcreditclient() {
        return this.idcreditclient;
    }
    
    public void setIdcreditclient(int idcreditclient) {
        this.idcreditclient = idcreditclient;
    }
    public int getIdsession() {
        return this.idsession;
    }
    
    public void setIdsession(int idsession) {
        this.idsession = idsession;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PayementcreditclientId) ) return false;
		 PayementcreditclientId castOther = ( PayementcreditclientId ) other; 
         
		 return (this.getIdcreditclient()==castOther.getIdcreditclient())
 && (this.getIdsession()==castOther.getIdsession());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcreditclient();
         result = 37 * result + this.getIdsession();
         return result;
   }   


}


