package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA


/**
 * Produit generated by hbm2java
 */
@SuppressWarnings("serial")
public class Produit implements java.io.Serializable {

	private int idproduit;
	private Categorie categorie;

	public Produit() {
	}

	public int getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(int idproduit) {
		this.idproduit = idproduit;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

}
