package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA


/**
 * Session generated by hbm2java
 */
@SuppressWarnings("serial")
public class Session implements java.io.Serializable {

	private int idsession;
	private Utilisateur utilisateur;
	private String datedebutsession;
	private String datefinsession;
	private Integer dureesession;
	

	public Session() {
	}

	public Session(int idsession, Utilisateur utilisateur) {
		this.idsession = idsession;
		this.utilisateur = utilisateur;
	}

	public Session(int idsession, Utilisateur utilisateur,
			String datedebutsession, String datefinsession, Integer dureesession) {
		this.idsession = idsession;
		this.utilisateur = utilisateur;
		this.datedebutsession = datedebutsession;
		this.datefinsession = datefinsession;
		this.dureesession = dureesession;
		
	}

	public int getIdsession() {
		return this.idsession;
	}

	public void setIdsession(int idsession) {
		this.idsession = idsession;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getDatedebutsession() {
		return this.datedebutsession;
	}

	public void setDatedebutsession(String datedebutsession) {
		this.datedebutsession = datedebutsession;
	}

	public String getDatefinsession() {
		return this.datefinsession;
	}

	public void setDatefinsession(String datefinsession) {
		this.datefinsession = datefinsession;
	}

	public Integer getDureesession() {
		return this.dureesession;
	}

	public void setDureesession(Integer dureesession) {
		this.dureesession = dureesession;
	}

	

}
