package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Typeutilisateur generated by hbm2java
 */
@SuppressWarnings("serial")
public class Typeutilisateur implements java.io.Serializable {

	private int idtypeutilisateur;
	private String libelletypeutilisateur;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Typeutilisateur() {
	}

	public Typeutilisateur(int idtypeutilisateur) {
		this.idtypeutilisateur = idtypeutilisateur;
	}

	public Typeutilisateur(int idtypeutilisateur,
			String libelletypeutilisateur, Set<Utilisateur> utilisateurs) {
		this.idtypeutilisateur = idtypeutilisateur;
		this.libelletypeutilisateur = libelletypeutilisateur;
		this.utilisateurs = utilisateurs;
	}

	public int getIdtypeutilisateur() {
		return this.idtypeutilisateur;
	}

	public void setIdtypeutilisateur(int idtypeutilisateur) {
		this.idtypeutilisateur = idtypeutilisateur;
	}

	public String getLibelletypeutilisateur() {
		return this.libelletypeutilisateur;
	}

	public void setLibelletypeutilisateur(String libelletypeutilisateur) {
		this.libelletypeutilisateur = libelletypeutilisateur;
	}

	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
