package com.mms.pojos;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Utilisateur generated by hbm2java
 */
@SuppressWarnings("serial")
public class Utilisateur implements java.io.Serializable {

	private int idutilisateur;
	private Typeutilisateur typeutilisateur;
	private String nomutilisateur;
	private String prenomutilisateur;
	private String loginutilisateur;
	private String telephoneutilisateur;
	private Date dateembaucheutilisateur;
	private Date datedepartutilisateur;

	public Utilisateur() {

	}

	public Utilisateur(int idutilisateur, Typeutilisateur typeutilisateur) {
		this.idutilisateur = idutilisateur;
		this.typeutilisateur = typeutilisateur;
	}

	public Utilisateur(int idutilisateur, Typeutilisateur typeutilisateur,
			String nomutilisateur, String prenomutilisateur,
			String loginutilisateur, String telephoneutilisateur,
			Date dateembaucheutilisateur, Date datedepartutilisateur) {
		this.idutilisateur = idutilisateur;
		this.typeutilisateur = typeutilisateur;
		this.nomutilisateur = nomutilisateur;
		this.prenomutilisateur = prenomutilisateur;
		this.loginutilisateur = loginutilisateur;
		this.telephoneutilisateur = telephoneutilisateur;
		this.dateembaucheutilisateur = dateembaucheutilisateur;
		this.datedepartutilisateur = datedepartutilisateur;

	}

	public int getIdutilisateur() {
		return this.idutilisateur;
	}

	public void setIdutilisateur(int idutilisateur) {
		this.idutilisateur = idutilisateur;
	}

	public Typeutilisateur getTypeutilisateur() {
		return this.typeutilisateur;
	}

	public void setTypeutilisateur(Typeutilisateur typeutilisateur) {
		this.typeutilisateur = typeutilisateur;
	}

	public String getNomutilisateur() {
		return this.nomutilisateur;
	}

	public void setNomutilisateur(String nomutilisateur) {
		this.nomutilisateur = nomutilisateur;
	}

	public String getPrenomutilisateur() {
		return this.prenomutilisateur;
	}

	public void setPrenomutilisateur(String prenomutilisateur) {
		this.prenomutilisateur = prenomutilisateur;
	}

	public String getLoginutilisateur() {
		return this.loginutilisateur;
	}

	public void setLoginutilisateur(String loginutilisateur) {
		this.loginutilisateur = loginutilisateur;
	}

	public String getTelephoneutilisateur() {
		return this.telephoneutilisateur;
	}

	public void setTelephoneutilisateur(String telephoneutilisateur) {
		this.telephoneutilisateur = telephoneutilisateur;
	}

	public Date getDateembaucheutilisateur() {
		return this.dateembaucheutilisateur;
	}

	public void setDateembaucheutilisateur(Date dateembaucheutilisateur) {
		this.dateembaucheutilisateur = dateembaucheutilisateur;
	}

	public Date getDatedepartutilisateur() {
		return this.datedepartutilisateur;
	}

	public void setDatedepartutilisateur(Date datedepartutilisateur) {
		this.datedepartutilisateur = datedepartutilisateur;
	}

}
