package com.mms.pojos;

import java.util.Date;

// Generated 25 nov. 2012 13:14:59 by Hibernate Tools 3.2.1.GA


/**
 * Vente generated by hbm2java
 */
public class Vente {

	private int numerovente;
	private Client client;
	private Session session;
	private Etat etat;
	private Double montantTotalVenteHt;
	private Double montantTotalVenteTtc;
	private Double montantTotalVenteTva;
	private Date datevente;

	public Vente() {
	}

	public int getNumerovente() {
		return this.numerovente;
	}

	public void setNumerovente(int numerovente) {
		this.numerovente = numerovente;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Session getSession() {
		return this.session;
	}

	public void setSession(Session session) {
		this.session = session;
	}

	public Etat getEtat() {
		return this.etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public Double getMontanttotalventeht() {
		return this.montantTotalVenteHt;
	}

	public void setMontanttotalventeht(Double montanttotalventeht) {
		this.montantTotalVenteHt = montanttotalventeht;
	}

	public Double getMontanttotalventettc() {
		return this.montantTotalVenteTtc;
	}

	public void setMontanttotalventettc(Double montanttotalventettc) {
		this.montantTotalVenteTtc = montanttotalventettc;
	}

	/**
	 * @return the montantTotalVenteTva
	 */
	public Double getMontantTotalVenteTva() {
		return montantTotalVenteTva;
	}

	/**
	 * @param montantTotalVenteTva
	 *            the montantTotalVenteTva to set
	 */
	public void setMontantTotalVenteTva(Double montantTotalVenteTva) {
		this.montantTotalVenteTva = montantTotalVenteTva;
	}

	public Date getDatevente() {
		return this.datevente;
	}

	public void setDatevente(Date datevente) {
		this.datevente = datevente;
	}

}
